# Generated by Django 4.2 on 2023-07-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('opassword', models.CharField(max_length=100)),
                ('owname', models.CharField(max_length=100)),
                ('owphone', models.CharField(max_length=20)),
                ('owapprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('uphone', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('pdescription', models.TextField()),
                ('pcapacity', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('programme', models.CharField(max_length=100)),
                ('appointmentStatus', models.CharField(default='Pending', max_length=20)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.printer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.user')),
            ],
        ),
    ]
