# Generated by Django 4.2 on 2023-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='pcapacity',
        ),
    ]
